site_name: Programación con Java
docs_dir: md
site_dir: docs
# theme: readthedocs
nav:
    - Home: index.md
    - U01:
        - 1.1 - Algoritmos y técnicas de representación: U01/U01.1.md
        - 1.2 - Programación con Java: U01/U01.2.md
        - 1.3 - Estructuras de control: U01/U01.3.md
    - U02:
        - 2.1 - Métodos: U02/U02.1.md
        - 2.2 - Strings: U02/U02.2.md
    - U03:
        - 3.1 - Arrays: U03/U03.1.md
    - About: about.md
extra_css:
  - css/extra.css